# Snowshoe hares at Bonanza Creek Experimental Forest
### Week 3 - Discussion section

![Snowshoe hare](https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg/960px-SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=thumbnail&_=20170313021652)
Photo credits: Alan Schmierer

In [13]:
import pandas as pd
import numpy as np

hares = pd.read_csv('data/55_Hare_Data_2012.txt')

In [3]:
hares.head()

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
0,11/26/1998,NaN,bonrip,1A,414D096A08,NaN,NaN,NaN,1370.0,160.0,NaN,917.0,51,Population
1,11/26/1998,NaN,bonrip,2C,414D320671,NaN,M,NaN,1430.0,NaN,NaN,936.0,51,Population
2,11/26/1998,NaN,bonrip,2D,414D103E3A,NaN,M,NaN,1430.0,NaN,NaN,921.0,51,Population
3,11/26/1998,NaN,bonrip,2E,414D262D43,NaN,NaN,NaN,1490.0,135.0,NaN,931.0,51,Population
4,11/26/1998,NaN,bonrip,3B,414D2B4B58,NaN,NaN,NaN,1710.0,150.0,NaN,933.0,51,Population

	date	time	grid	trap	l_ear	r_ear	sex	age	weight	hindft	notes	b_key	session_id	study
Column Name:	date  
time  
grid  
trap  
l_ear  
r_ear  
sex  
age  
weight  
hindft  
notes  
b_key  
session_id  
study  
Definition:	Date	Time	name of trapping grid	trap ID	left ear tag	right ear tag	sex of hare captured	age of capture	weight of hare	hind foot	notes on capture	unique animal identifier	unique session idenifier (A session is defined as multiple consecutive trap nights at a given site.)	The study type of this particular trapping session.

In [4]:
hares.isna().count()

date          3380
time          3380
grid          3380
trap          3380
l_ear         3380
r_ear         3380
sex           3380
age           3380
weight        3380
hindft        3380
notes         3380
b_key         3380
session_id    3380
study         3380
dtype: int64

Location: Bonanza Creek Experimental Forest

In [5]:
hares.shape

(3380, 14)

In [6]:
hares['age'].unique()

array([nan, 'J', 'A', 'a 1 yr.', 'a 3/4 yr.', 'a 1 yr', '1 yr', '1 yr.',
       '2 yrs.', '2 yrs', 'a 2 yrs.', '2.25 yrs', '3.5 yrs.', '3 yrs.',
       '2.5 yrs', '3.25 yrs.', 'A 1.5', '?', 'U', 'j', 'a', 'u', 'J 3/4',
       'A 3/4', 'A 1/2', '3/4/2013', '1/4/2013', '1/2/2013', '1', '1.25',
       '1.5'], dtype=object)

In [7]:
hares.dtypes

date           object
time           object
grid           object
trap           object
l_ear          object
r_ear          object
sex            object
age            object
weight        float64
hindft        float64
notes          object
b_key         float64
session_id      int64
study          object
dtype: object

## 4. Detecting messy values

| Values      | Definition |
| ----------- | ----------- |
| f      | female       |
| m   | male        |
| m?   | male not confirmed       |

In [10]:
hares['sex'].unique()

array([nan, 'M', 'F', '?', 'F?', 'M?', 'pf', 'm', 'f', 'f?', 'm?', 'f ',
       'm '], dtype=object)

In [12]:
hares['sex'].value_counts(dropna=False)

sex
F      1161
M       730
f       556
m       515
NaN     352
?        40
F?       10
f         4
m         4
f?        3
M?        2
m?        2
pf        1
Name: count, dtype: int64

## 6. Clean values

# Python program to illustrate
# Add a new column  in Pandas 
# Data Frame Using a Dictionary

import pandas as pd

data_frame = pd.DataFrame([[i] for i in range(7)], columns =['data'])

# Introducing weeks as dictionary
weeks = {0:'Sunday', 1:'Monday', 2:'Tuesday', 3:'Wednesday', 
4:'Thursday', 5:'Friday', 6:'Saturday'}

# Mapping the dictionary keys to the data frame.
data_frame['new_data_1'] = data_frame['data'].map(weeks)
print (data_frame)

In [56]:
hares['sex'] = hares['sex'].str.lower().str.strip()
# print(sum(hares['sex'].value_counts()))
# print(sum(hares['sex']=='?'))

sex_dict = {'f?':'female',
            'f':'female',
            'pf':'female',
            'm?':'male',
            'm':'male',
            '?':np.nan
            }

hares['sex_simple'] = hares['sex'].map(sex_dict)
# print(sum(hares['sex_simple'].value_counts())+sum(hares['sex']=='?'))
hares['sex_simple'].value_counts(dropna=False)

sex_simple
female    1735
male      1253
NaN        392
Name: count, dtype: int64

## 7. Calculate mean weight

In [57]:
hares.columns

Index(['date', 'time', 'grid', 'trap', 'l_ear', 'r_ear', 'sex', 'age',
       'weight', 'hindft', 'notes', 'b_key', 'session_id', 'study',
       'sex_simple'],
      dtype='object')

In [59]:
hares[['weight','sex_simple']].groupby('sex_simple').mean()

                 weight
sex_simple
female      1363.388560
male        1350.194643