# Water conflicts in the Colorado River Basin

## 1. Archive exploration

a. Exploring the dataset  
    i. the data is collected from the Colorado River Basin.  
    ii. The dataset was collected from 2005 - 2021.  
    iii. The author's perceived value of the work is to focus on the water resource crisis.  
b. The Colorado River Basin dataset from the USGS aims to highlight the injustice in water resource distribution.

## 2. Data loading

In [19]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/Colorado River Basin Water Conflict Table.csv")

## 3. Preliminary data exploration

In [3]:
df.columns

Index(['Event', 'Search Source', 'Newspaper', 'Article Title', 'Duplicate',
       'Report Date', 'Report Year', 'Event Date', 'Event Day', 'Event Month',
       'Event Year', 'Conflict Present', 'Crisis Present', 'Basin', 'HUC6',
       'HUC2', 'Place', 'County', 'County FIPS', 'State', 'State FIPS',
       'Urban or Rural', 'Issue Type', 'Event Summary', 'Stakeholders',
       'Intensity Value', 'Comments', 'Related Observation Themes',
       'Article Text Search - water quality',
       'Article Text Search - invasive species',
       'Article Text Search - conservation', 'Article Text Search - drought',
       'Article Text Search - flood',
       'Article Text Search - ground water depletion',
       'Article Text Search - depletion',
       'Article Text Search - infrastructure',
       'Article Text Search - fish passage',
       'Article Text Search - instream water rights',
       'Article Text Search - water rights',
       'Article Text Search - intergovernmental',
       'Article Text Search - water transfers',
       'Article Text Search - navigation', 'Article Text Search - fish',
       'Article Text Search - invasive', 'Article Text Search - diversion',
       'Article Text Search - water diversion',
       'Article Text Search - instream', 'Article Text Search - aquatic'],
      dtype='object')

In [4]:
df.shape

(268, 48)

In [5]:
df.head()

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,...,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,...,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,...,18,0,0,0,0,0,0,0,0,0

In [6]:
df.count()

Event                                           268
Search Source                                   268
Newspaper                                       268
Article Title                                   268
Duplicate                                       267
Report Date                                     267
Report Year                                     265
Event Date                                      248
Event Day                                        18
Event Month                                     212
Event Year                                      257
Conflict Present                                252
Crisis Present                                  254
Basin                                           250
HUC6                                            110
HUC2                                            250
Place                                           254
County                                            8
County FIPS                                       8
State                                           178
State FIPS                                      178
Urban or Rural                                  254
Issue Type                                      255
Event Summary                                   256
Stakeholders                                    255
Intensity Value                                 255
Comments                                        190
Related Observation Themes                       86
Article Text Search - water quality             268
Article Text Search - invasive species          268
Article Text Search - conservation              268
Article Text Search - drought                   268
Article Text Search - flood                     268
Article Text Search - ground water depletion    268
Article Text Search - depletion                 268
Article Text Search - infrastructure            268
Article Text Search - fish passage              268
Article Text Search - instream water rights     268
Article Text Search - water rights              268
Article Text Search - intergovernmental         268
Article Text Search - water transfers           268
Article Text Search - navigation                268
Article Text Search - fish                      268
Article Text Search - invasive                  268
Article Text Search - diversion                 268
Article Text Search - water diversion           268
Article Text Search - instream                  268
Article Text Search - aquatic                   268
dtype: int64

In [7]:
df.dtypes

Event                                             int64
Search Source                                    object
Newspaper                                        object
Article Title                                    object
Duplicate                                        object
Report Date                                      object
Report Year                                     float64
Event Date                                       object
Event Day                                       float64
Event Month                                     float64
Event Year                                      float64
Conflict Present                                 object
Crisis Present                                   object
Basin                                            object
HUC6                                             object
HUC2                                             object
Place                                            object
County                                           object
County FIPS                                     float64
State                                            object
State FIPS                                       object
Urban or Rural                                   object
Issue Type                                       object
Event Summary                                    object
Stakeholders                                     object
Intensity Value                                 float64
Comments                                         object
Related Observation Themes                       object
Article Text Search - water quality               int64
Article Text Search - invasive species            int64
Article Text Search - conservation                int64
Article Text Search - drought                     int64
Article Text Search - flood                       int64
Article Text Search - ground water depletion      int64
Article Text Search - depletion                   int64
Article Text Search - infrastructure              int64
Article Text Search - fish passage                int64
Article Text Search - instream water rights       int64
Article Text Search - water rights                int64
Article Text Search - intergovernmental           int64
Article Text Search - water transfers             int64
Article Text Search - navigation                  int64
Article Text Search - fish                        int64
Article Text Search - invasive                    int64
Article Text Search - diversion                   int64
Article Text Search - water diversion             int64
Article Text Search - instream                    int64
Article Text Search - aquatic                     int64
dtype: object

In [8]:
df.isna().sum()

Event                                             0
Search Source                                     0
Newspaper                                         0
Article Title                                     0
Duplicate                                         1
Report Date                                       1
Report Year                                       3
Event Date                                       20
Event Day                                       250
Event Month                                      56
Event Year                                       11
Conflict Present                                 16
Crisis Present                                   14
Basin                                            18
HUC6                                            158
HUC2                                             18
Place                                            14
County                                          260
County FIPS                                     260
State                                            90
State FIPS                                       90
Urban or Rural                                   14
Issue Type                                       13
Event Summary                                    12
Stakeholders                                     13
Intensity Value                                  13
Comments                                         78
Related Observation Themes                      182
Article Text Search - water quality               0
Article Text Search - invasive species            0
Article Text Search - conservation                0
Article Text Search - drought                     0
Article Text Search - flood                       0
Article Text Search - ground water depletion      0
Article Text Search - depletion                   0
Article Text Search - infrastructure              0
Article Text Search - fish passage                0
Article Text Search - instream water rights       0
Article Text Search - water rights                0
Article Text Search - intergovernmental           0
Article Text Search - water transfers             0
Article Text Search - navigation                  0
Article Text Search - fish                        0
Article Text Search - invasive                    0
Article Text Search - diversion                   0
Article Text Search - water diversion             0
Article Text Search - instream                    0
Article Text Search - aquatic                     0
dtype: int64

In [9]:
df['Issue Type'].value_counts()

Issue Type
Drought                                                                       66
Water rights more generally                                                   51
Conservation                                                                  43
Intergovernmental issues                                                      43
Infrastructure issues                                                         15
Water quality                                                                 10
Water transfers                                                                6
Instream water rights                                                          6
Flood                                                                          4
Intergovernmental issues: Water rights more generally                          2
Intergovernmental issues: Drought                                              1
Intergovernmental issues: Water transfers                                      1
Intergovernmental issues: Conservation                                         1
Conservation; Drought                                                          1
Fish passage                                                                   1
Ground water depletion                                                         1
Conservation; Water rights more generally                                      1
Drought; Water quality; Water rights more generally; Infrastructure issues     1
Conservation; Ground water depletion                                           1
Name: count, dtype: int64

## 4. Location column descriptions

In [14]:
df['State'].value_counts()

State
AZ                            66
CO                            34
UT                            27
NV                            10
CA                             7
NM                             6
AZ; CA                         4
AZ; UT                         3
AZ; CA; CO; NV; NM; UT; WY     3
AZ; NV                         2
NV; AZ                         2
CO; AZ                         2
CO; UT; WY; NM                 2
AZ; NM                         1
CA; NV; AZ                     1
WY; UT; CO                     1
UT; CO; WY                     1
CO; WY                         1
AZ; CA; NV                     1
UT; AZ                         1
AZ; CO; NM; UT                 1
OH; UT                         1
TX                             1
Name: count, dtype: int64

In [15]:
df['Place'].unique()

array(['Durango, CO', 'Great Salt Lake',
       'Colorado River Indian Reservation',
       'Southern Ute Indian Reservation', 'State of Arizona',
       'Entire Colorado River Basin', 'All of Colorado River Basin',
       'Farmington, OH; Great Salt Lake', 'Navajo Nation; Window Rock AZ',
       'Bullhead City, AZ re: All of Colorado R. Basin', 'Phoenix, AZ',
       'Ute Tribe, Utah', 'Denver, CO; Shoshone power plant',
       'AZ, CO, NM, UT, Southern Ute Tribe, Ute Mountain tribe, Navajo Nation',
       'Colorado River Basin', 'Laughlin, AZ',
       'Colorado River Indian Reservation; Parker, AZ',
       'CA - Imperial Irrigation District', 'Flagstaff, AZ',
       'Glen Canyon Dam, Lake Powell, UT; AZ', 'Needles, CA',
       'AZ, NV, Mexico', 'CO, UT, WY, NM', 'Las Vegas, Southern CA; AZ',
       'Sacaton/Gila R. Indian Reservation', 'Boulder, CO', 'Lees Ferry',
       'AZ', 'Lake Powell (UT, AZ)', 'Glenwod Springs',
       'Multiple waterways in UT ', 'St. Michaels, AZ',
       'The Front Range, CO/WY', 'CO', 'Flagstaff, AZ; UT',
       'Las Vegas, Flagstaff, AZ', 'CO (also Phoenix/Tucson, AZ',
       'Window Rock, AZ; Navajo Nation', 'Upper basin states',
       'Greeley, CO', 'AZ, CA, CO, NV, NM, UT, WY',
       'Scottsdale, Tucson, Phoenix, AZ', 'AZ, CA, NV', 'AZ; CA',
       'Las Vegas, NV', 'Hermosa Creek',
       'Phoenix, AZ/AZ; CA; CO, NV; NM; UT, WY', 'Animas River',
       'Lake Mead', 'Long Hollow Dam', 'White River', 'Glendale',
       'Colorado River', 'Southwestern US', 'Garfield County, CO',
       'San Juan River', 'Colorado River System',
       'Navajo Nation, Hopi Reservation', 'Gila River Indian Reservation',
       'Navajo Nation', 'Green River', 'Routt County, CO',
       'Pinal County, AZ', 'Pecos River', 'Colorado State',
       'Navajo/Hopi Reservations, Lower Colorado River', 'Flaming Gorge',
       'Lake Powell', 'Lake Powell, Lake Mead, Gila River',
       'Salt Lake City', 'State of Colorado', 'Pheonix, AZ',
       'Boulder City, NV', 'Salton Sea', 'Mancos River Watershed',
       'California State', 'Washington D.C.', 'Navajo/Hopi Nations',
       'Animas River including Junction and Lightner Creeks from Bakers Bridge to the New Mexico line, La Plata RIver from Mayday to the New Mexico State line, Vellecito Creek, Pine River from Vallecito to the Southern Ute Indian Tribe reservation south of Bayfield, Florida River,',
       'The application for Utah water rights requests 55,000 acre feet of water from the Green River with two pump stations located five miles from the Colorado state line in Dagget County, Utah, on Bureau of Land Management land. The water would then run through a hydroelectric facility before being piped nearly 500 miles northeast into Wyoming and then south down the Colorado Front Range',
       nan, 'Denver, CO', 'Yuma, AZ', 'Yampa Valley, CO', 'Tuscon, AZ',
       'Central Arizona Project, AZ',
       'San Juan County, San Juan River, Navajo Nation',
       'Hoover Dam, Clark County, NV', 'Green River Community, Utah',
       'San Juan River and Lake Powell', 'Navajo Nation, AZ',
       'White Mountain Apache lands Northeast/central AZ, CRIT lands along western edge of AZ and into CA',
       'South of the Seedskadee National Wildlife Refuge',
       'State of California, Nevada, Arizona', 'Glen Canyon Dam',
       'Yuma County, AZ', 'New Mexico, Arizona',
       'Wyoming, Utah, Colorado', 'Glen Canyon Dam, Grand Canyon',
       'Animas River near Silverton, San Juan River to Lake Powell',
       'Meeker, Colorado', 'Arizona ',
       'Arizona, California, Colorado, Nevada, New Mexico, Utah, Wyoming',
       'Lower Basin', 'Navajo Generating Station, near Page, AZ',
       'La Plata County, Animas River Valley', 'Cibola, AZ',
       'Lake Mead; Bullhead City, AZ', 'Colorado River Delta',
       'Little Colorado River Basin', 'State of Utah',
       'San Juan River; Navajo Nation; New Mexico',
       'Colorado; Phoenix AZ', 'Arizona',
       'Wayne County, Utah; Green River',
       'Lower Arkansas Valley Water Conservancy District',
       'Upper Colorado River Basin', 'Green River; Utah',
       'Lower Colorado River Basin', 'Salton Sea; California',
       'Arizona; entire Colorado River Basin',
       'Rio Blanco Water Conservancy District; State of Colorado',
       'Navajo and Hopi Nations/Little Colorado River', 'Bear River',
       'Utah', 'Scottsdale, AZ', 'Colorado ', 'Grand Valley, CO',
       'Austin, TX', 'Western Slope, CO', 'Salt River', 'Green River, UT',
       'Tempe, AZ', 'Yuma, AZ ', 'Glen Canyon Dam, AZ',
       'State of Arizona, State of California'], dtype=object)

In [18]:
df['Conflict Present'].value_counts()

Conflict Present
Y    145
N    107
Name: count, dtype: int64

## 5. String accessor for pandas.Series

In [20]:
# Example series
s = pd.Series(['California; Nevada', 'Arizona', np.nan, 'Nevada; Utah'])
s

0    California; Nevada
1               Arizona
2                   NaN
3          Nevada; Utah
dtype: object

In [21]:
# Use str accessor with additional methods to perform string operations
s.str.split(';')

0    [California,  Nevada]
1                [Arizona]
2                      NaN
3          [Nevada,  Utah]
dtype: object

In [23]:
s.str.split('; ').explode()

0    California
0        Nevada
1       Arizona
2           NaN
3        Nevada
3          Utah
dtype: object

## 6. Examine state codes

In [68]:
df2 = df[['Place','State','Conflict Present']].copy()
df2

                                     Place   State Conflict Present
0                              Durango, CO      CO                Y
1                              Durango, CO      CO                Y
2                          Great Salt Lake      UT                N
3        Colorado River Indian Reservation     NaN                N
4          Southern Ute Indian Reservation     NaN                Y
..                                     ...     ...              ...
263                      Western Slope, CO      CO                N
264                      Western Slope, CO      CO                N
265  State of Arizona, State of California  AZ; CA                Y
266                    Glen Canyon Dam, AZ      AZ                N
267                       State of Arizona      AZ                N

[268 rows x 3 columns]

In [70]:
conflict_state = df2.loc[df['Conflict Present'] == 'Y', 'State']
conflict_state = conflict_state.loc[conflict_state.notna()]
conflict_state

0          CO
1          CO
5          AZ
11     OH; UT
12         UT
        ...
255        UT
257        AZ
258        UT
262        AZ
265    AZ; CA
Name: State, Length: 98, dtype: object

In [71]:
conflict_state.str.split('; ').explode().unique()

array(['CO', 'AZ', 'OH', 'UT', 'CA', 'NV', 'WY', 'NM'], dtype=object)